[project]
name = "backend"
version = "0.1.0"
description = "LifeLessonPlan 老師後台 API"
readme = "README.md"
authors = [
    { name = "sstc02750963", email = "sstc02750963@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "bcrypt>=5.0.0",
    "fastapi[standard]>=0.141.1",
    "pymysql>=1.2.0",
    "python-dotenv>=1.2.3",
]

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
